FROM ubuntu:18.04
RUN export DEBIAN_FRONTEND=noninteractive && \
    apt update && \
    apt install -y \
        git \
        python3-pip && \
    pip3 install \
        keyring \
        requests \
        requests-mock \
        pytest \
        pylint==1.9.3 \
        astroid==1.6.5 \
        flask==1.1.1 \
        werkzeug==0.15.5
